### ISSUE TITLE
Suggestion: Include README and Necessary Data Files

### ISSUE THREAD

**Issue by Caealana** [albert-kevin/intro-data-capstone-musclehub#1]
Just a minor suggestion:
For future readers of your project, it would be helpful to have a README that gives a summary of your project. You could also include the data files in your project repository so readers(those not from Codecademy) can run your project.

[Here](https://www.drupal.org/docs/develop/documenting-your-project/readme-template) is a basic template for a README.

**Comment by albert-kevin** [comment]
Thank you for this suggestion,
I have added a readme.md on the main page
The remaining files are uploaded.

PS: I leave it to you to close this Issue ?
