### ISSUE TITLE
Nice Use of Comments

### ISSUE THREAD

**Issue by Caealana** [albert-kevin/intro-data-capstone-musclehub#5]
https://github.com/albert-kevin/intro-data-capstone-musclehub/blob/228804768101138ce967fa2406431054b4ef1f63/albert_kevin/Albert_Kevin_MuscleHub_feb-2018.py#L254-L257

Good use of comments to make note of things to look out for/ make note of when looking at your code. You could also use comments to give brief summaries of what you're trying to accomplish with a particular code chunk (though Codecademy fills in most of that for you).

**Comment by albert-kevin** [comment]
I included this to communicate with the reader as well for myself what I learned.
In the future ~80% of the time should go to documentation, pythonic coding style, clear comments.
I am also aware of the comment method """ or ''' for multiple lines
for SQL code we use  -- for comments
Thank you for the remark
