### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by Caealana** [albert-kevin/intro-data-capstone-musclehub#6]
https://github.com/albert-kevin/intro-data-capstone-musclehub/blob/228804768101138ce967fa2406431054b4ef1f63/albert_kevin/Albert_Kevin_MuscleHub_feb-2018.py#L344-L355

You submitted a great project! Your code is clean and easily readable. I did not find any major errors that would cause incorrect results. Your comments were incredibly informative demonstrated your understanding of the statistics concepts needed for this project. 

For your slide presentation:
It looks professional with a nice layout. Your introduction and breakdown of context information is good. The figure you created in your Objectives slide is helpful. Some of the grammar on your objectives slide could be fixed:
"is filling out application forms influence the amount of membership payments" to
"does filling out application forms influence the amount of membership payments"
You mention groups A and B, but you dont mention how those groups were decided or what kind of members are in each group.
Good job on stating your null and alternative hypothesis clearly. Your analysis is detailed and interesting. You went above and beyond what the assignment called for in your analysis and in creating the figures.

**Comment by albert-kevin** [comment]
Thank you for your review and confirmation that
I was able to analyze correct.
This in turn confirms the quality of the course that
it worked for me to learn correctly.

Indeed, fixed the grammar as suggested and replaced the *.pdf
Changed color in slide 3:
WITH TEST is called group A
NO TEST is called group B

I actually hope to see some slide presentations from finished students.
I have learned that a presentation should be compact and visual.

I have some remaining questions:
1. my conclusions are correct ?
2. slide 4 I mention sample size, I am confused.
I have tried to calculate the sample size needed for the A/B tests.
I learned from the course that you are not allowed to go below or above
the sample size or your analysis is false.
But then on the other hand the chi square takes the sample size into account.
I have noticed the following thoughts:
for example the sample size for application forms:
- baseline: ~10%
- significance: 95%
- detectable effect: (13% - 10%) / 10% = 30%
answer sample calculator = 2100 samples
thus A/B = 2 x 2100 = 4200 samples, did we risk being oversampled ?

doing the same for the second hypothesis:
- baseline: ~77%
- significance: 95%
- detectable effect: (80% - 77%) / 77% = 4%
answer sample calculator: 3900 samples
thus A/B = 2 x 3900 = 7800 samples, did we risk having not enough samples ?

doing the same for the third hypothesis:
- baseline: ~8%
- significance: 95%
- detectable effect: (10% - 8%) / 8% = 25%
answer sample calculator: 3900 samples
thus A/B = 2 x 3900 = 7800 samples, did we risk having not enough samples ?

https://s3.amazonaws.com/codecademy-content/courses/learn-hypothesis-testing/a_b_sample_size/index.html

Note: I leave it to you to close the incident ?

**Comment by Caealana** [comment]
@albert-kevin I apologize for the delay in my response! You have some great questions. I just want to let you know I have seen your questions and I will be responding in the next couple of days. I am a bit busy with travel at the moment, and I need to meet some deadlines for leaving first round comments for a couple of other projects, but I will get back to you as soon as I can.

**Comment by albert-kevin** [comment]
Hi,
Could you please find time to discuss these questions ?

**Comment by Caealana** [comment]
Hi again,
I apologize deeply for the delay.
Here are some slideshows from other finished students:
https://github.com/jkang215/intro-data-capstone-musclehub/blob/master/musclehub_submission/MuscleHub%20AB%20Test%20Presentation.pdf
https://github.com/rashidjb/intro-data-capstone-musclehub/blob/master/Submission/musclehub_presentation.pdf

1) Your conclusions are correct. I would just caution that you take extra care with your wording in your conclusions, as many statisticians are very picky about what exact knowledge you gain from the hypothesis tests. 
For example:
<img width="715" alt="screenshot at mar 28 18-17-23" src="https://user-images.githubusercontent.com/14001120/38056948-4e4a99d4-32b4-11e8-942e-12bb6ef69db3.png">
We can't say for certain that doing a test has no impact on the outcome; we can only say that it has no statistically significant impact on the outcome. 

2) Generally, we won't have issues with larger sample sizes as long as they don't get overwhelmingly large. [This](https://stats.stackexchange.com/questions/125750/sample-size-too-largel) discussion gives a thorough overview of what issues larger samples can cause and how to adjust for larger sample sizes in your tests. "As we continue increasing the sample size and the length of observation, the mean of our observations will get closer and closer to the true mean of the population."]( https://conversionsciences.com/blog/ab-testing-statistics/). This link will take you to an article that gives a slightly more in-depth overview of A/B testing and the statistics behind it. 

On not having enough samples - yes, we would generally need to be able to collect enough samples to reduce the risk of error. There are some changes you can make to the test structure to try to account for a smaller sample size, like adjusting the significance level we will use.

**Comment by albert-kevin** [comment]
Thank you so much for your feedback !
